version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/build/Dockerfile
    depends_on:
      - mysql
    ports:
      - 80:8080
    volumes:
      - ./:/go/src
    command: realize start --run
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample_dev
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./tmp/docker/mysql:/var/lib/mysql:delegated
    ports:
      - 3306:3306
