version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/build/Dockerfile
    depends_on:
      - mysql
    ports:
      - 80:8080
  mysql:
    image: mysql:5.6
    container_name: godockerDB
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample_dev
    volumes:
      - ./tmp/docker/mysql:/var/lib/mysql:delegated
    ports:
      - 3306:3306
